'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
exports.run=async host=>{
 const {win,app,storage}=host;for(let i=0;i<300&&!host.getState().ready;i++)await sleep(50);assert.ok(host.getState().ready,'Desktop renderer did not start');
 const snapshot=()=>win.webContents.executeJavaScript('petApp.snapshot()'),point=()=>win.webContents.executeJavaScript('petApp.grabPoint()');
 const report={passed:false,platform:process.platform,versions:process.versions,checks:[],errors:[]};
 const check=name=>report.checks.push(name);await sleep(200);let s=await snapshot();assert.ok(s.ready);assert.equal(s.cornerAlpha,0);assert.ok(Math.abs(s.floorPixel-host.getState().floorPixel)<.1,'Canvas/native floor metrics disagree');assert.ok(win.isAlwaysOnTop(),JSON.stringify({host:host.getState(),visible:win.isVisible(),top:win.isAlwaysOnTop()}));check('transparent canvas and native topmost window');
 let b=win.getBounds();host.setCursor({x:b.x+2,y:b.y+2});await sleep(180);assert.ok(host.getState().ignored);check('transparent region enables native click-through');
 for(const id of ['idle','hop','happy_bounce','head_juggle','sway','proud_hops','stunned','shocked','grin','determined']){host.getMenu().getMenuItemById('act-'+id).click();await sleep(120);assert.equal((await snapshot()).animation,id);}
 check('all ten ordinary action and expression clips run from tray menu');
 host.command('head_juggle');await sleep(150);report.volleyball={samples:0,minDiameter:Infinity,maxDiameter:0,minTop:Infinity};
 for(let i=0;i<32;i++){const ball=(await snapshot()).volleyball;assert.ok(ball,'Volleyball not shown');assert.ok(ball.diameter>=(770*2/3)*.944&&ball.diameter<=(770*2/3)*1.056,'Volleyball does not match revised size');assert.ok(ball.top>=0&&ball.left>=0&&ball.right<=ball.canvasWidth&&ball.bottom<=ball.canvasHeight,'Volleyball clipped by native window');report.volleyball.samples++;report.volleyball.minDiameter=Math.min(report.volleyball.minDiameter,ball.diameter);report.volleyball.maxDiameter=Math.max(report.volleyball.maxDiameter,ball.diameter);report.volleyball.minTop=Math.min(report.volleyball.minTop,ball.top);if(i===4)fs.writeFileSync(path.join(storage,'desktop-juggle.png'),Buffer.from((await win.webContents.executeJavaScript('petApp.png()')).split(',')[1],'base64'));await sleep(90);}
 check('volleyball at two thirds of head width stays inside the native canvas throughout repeated bounces');host.command('idle');await sleep(160);
 if(app.commandLine.hasSwitch('ball-size-only')){report.errors=host.getErrors();assert.equal(report.errors.length,0);report.passed=true;report.final=host.getState();fs.writeFileSync(path.join(storage,'volleyball-validation.json'),JSON.stringify(report,null,2)+'\n');app.exit(0);return;}
 for(const id of ['stunned','shocked','grin','determined']){host.getMenu().getMenuItemById('expr-'+id).click();await sleep(100);s=await snapshot();assert.equal(s.attachments.eye_L,'eye_L_'+id);assert.equal(s.attachments.mouth,'mouth_'+id);}
 host.getMenu().getMenuItemById('expr-auto').click();host.command('idle');await sleep(180);check('independent expression selection and automatic reset');
 async function down(){const p=await point();b=win.getBounds();host.setCursor({x:b.x+p.x,y:b.y+p.y});await sleep(150);assert.equal(host.getState().ignored,false,'Opaque character does not accept input');win.webContents.sendInputEvent({type:'mouseMove',x:Math.round(p.x),y:Math.round(p.y)});win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,x:Math.round(p.x),y:Math.round(p.y)});return p;}
 async function up(){const p=await point();win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,x:Math.round(p.x),y:Math.round(p.y)});}
 await down();await sleep(80);await up();await sleep(220);assert.equal((await snapshot()).phase,'idle');check('short click stays out of claw interaction');host.command('idle');await sleep(200);
 const p=await down();await sleep(800);s=await snapshot();assert.equal(s.phase,'held');assert.equal(s.animation,'drag_hold');assert.equal(Object.entries(s.attachments).filter(([name,value])=>name.startsWith('claw_')&&value).length,8);
 // Move inward from the default right-hand position, away from the display edge.
 const start=win.getBounds();let maximumSwing=0;for(let i=1;i<=15;i++){host.setCursor({x:start.x+p.x-i*8,y:start.y+p.y-i*12});await sleep(30);maximumSwing=Math.max(maximumSwing,Math.abs((await snapshot()).swing));}
 const lifted=win.getBounds(),dragState=await snapshot();assert.ok(lifted.y<start.y-140,'Native window did not lift: '+JSON.stringify({start,lifted,dragState}));assert.ok(lifted.x<start.x-40,'Native window did not follow horizontally: '+JSON.stringify({start,lifted,dragState}));assert.ok(Math.abs(lifted.width-start.width)<=1,'Window width grew during drag');assert.ok(Math.abs(lifted.height-start.height)<=1,'Window height grew during drag');assert.ok(maximumSwing>1&&maximumSwing<=9.001,'Drag swing out of range: '+maximumSwing);
 check('300 ms hold shows all claw parts and moves the real Windows window');report.drag={from:start,held:lifted,maximumSwingDegrees:maximumSwing};
 fs.writeFileSync(path.join(storage,'desktop-held.png'),Buffer.from((await win.webContents.executeJavaScript('petApp.png()')).split(',')[1],'base64'));
 await up();await sleep(80);assert.equal((await snapshot()).phase,'dropping');await sleep(2200);s=await snapshot();assert.equal(s.phase,'idle');assert.equal(s.animation,'idle');assert.equal(Object.entries(s.attachments).filter(([name,value])=>name.startsWith('claw_')&&value).length,0);b=win.getBounds();const native=host.getState();assert.ok(Math.abs(b.y+native.floorPixel-(native.workArea.y+native.workArea.height))<1.1);
 check('release opens the claw, falls to display work area and returns to idle');
 win.focus();await sleep(200);await down();await sleep(800);assert.equal((await snapshot()).phase,'held');
 const {BrowserWindow}=require('electron');const focusTarget=new BrowserWindow({width:160,height:90,show:false,skipTaskbar:true,webPreferences:{sandbox:true}});await focusTarget.loadURL('data:text/html,<title>Desktop pet focus test</title>');focusTarget.show();focusTarget.focus();await sleep(2200);
 const afterBlur=await snapshot();focusTarget.destroy();assert.equal(afterBlur.phase,'idle','Focus loss failed: '+JSON.stringify({focused:win.isFocused(),phase:afterBlur.phase,host:host.getState()}));check('another native window taking focus safely releases the pet');
 host.getMenu().getMenuItemById('size-220').click();await sleep(350);assert.ok(win.getBounds().height<start.height);const small=host.getState();assert.ok(Math.abs(small.bounds.y+small.floorPixel-(small.workArea.y+small.workArea.height))<1.1);host.getMenu().getMenuItemById('size-300').click();await sleep(350);check('native resize keeps feet on the desktop floor');
 host.getMenu().getMenuItemById('visibility').click();assert.equal(win.isVisible(),false);await sleep(100);host.getMenu().getMenuItemById('visibility').click();assert.equal(win.isVisible(),true);await sleep(150);check('tray hide and show');
 fs.writeFileSync(path.join(storage,'desktop-idle.png'),Buffer.from((await win.webContents.executeJavaScript('petApp.png()')).split(',')[1],'base64'));
 s=await snapshot();assert.ok(Math.abs(s.floorPixel-host.getState().floorPixel)<.1,'Canvas/native floor metrics disagree after resizing');report.errors=host.getErrors();assert.equal(report.errors.length,0,'Electron reported errors');report.passed=true;report.final=host.getState();fs.writeFileSync(path.join(storage,'desktop-validation.json'),JSON.stringify(report,null,2)+'\n');app.exit(0);
};
